### ISSUE TITLE
Broken on Clutter 1.21.8+

### ISSUE THREAD

**Issue by nikolowry** [AMDG2/GnomeShell_DynamicTopBar#10]
LookingGlass error message:
"this._metaWindow.get_outer_rect is not a function"

Screenshot:
![screenshot from 2015-03-24 17-15-19](https://cloud.githubusercontent.com/assets/597310/6813147/bddecc08-d249-11e4-84ce-953e8429c0be.png)

---

Keep up the good work, very subtle extension but adds a lot to shell's UI/UX!

**Comment by ianbrunelli** [comment]
That's strange... It's working fine for me on GNOME Shell 3.15.91.

**Comment by nikolowry** [comment]
I'm on the latest and my apologizes, I posted this in a rush. The actual breakage happens with the latest Clutter.

**Comment by AMDG2** [comment]
Ok, I would have to investigate on this, but I have a huge problem. My computer just die, and I don't have money to buy another one. So I fallback on an old netbook, which can't run Gnome Shell fluidly. If someone made a pull request I can accept it ;)

**Comment by nikolowry** [comment]
I'm going to investigate further this weekend and if I find a solution I will make a pull request. However, I'll need to install some VM's for testing as I'm on Arch and using the git/bleeding-edge of every package.

The bug probably won't affect most people for months - that is until their packages are updated per their distro repos schedule.

**Comment by AMDG2** [comment]
Thanks for your time !

**Comment by ianbrunelli** [comment]
Okay, fixed this.

I'll do a PR in some minutes.

**Comment by AMDG2** [comment]
Fixed by version [3.1](https://github.com/AMDG2/GnomeShell_DynamicTopBar/releases/tag/3.1)
