### ISSUE TITLE
Gnome 3.16 support

### ISSUE THREAD

**Issue by varemenos** [AMDG2/GnomeShell_DynamicTopBar#13]
Could you please add support for 3.16?

**Comment by spaceisstrange** [comment]
Any news? @cork solution makes the extension avaliable to install, but the bar does not turn black when applications maximizes.

**Comment by ianbrunelli** [comment]
@spaceisstrange Pull request #11 fixes this. I'm surprised to see it isn't merged yet.

You can fix it manually by editing the file `extension.js` and replacing the line `global.screen.get_monitor_index_for_rect(this._metaWindow.get_outer_rect());` with `global.screen.get_monitor_index_for_rect(this._metaWindow.get_frame_rect());`.
