### ISSUE TITLE
Don't make whole corners invisible, just make their BG transparent

### ISSUE THREAD

**Issue by tengwar** [AMDG2/GnomeShell_DynamicTopBar#15]
Currently  you seem to hide whole corners which leads to glitches like this:
![zrzut ekranu z 2015-04-29 12 54 47](https://cloud.githubusercontent.com/assets/7026772/7389823/2acc01d4-ee72-11e4-8db0-d3f3fe143946.png)
This is an Overview button; notice the gap on the left - normally it looks like this:
![zrzut ekranu z 2015-04-29 13 19 56](https://cloud.githubusercontent.com/assets/7026772/7389863/793b744e-ee72-11e4-8b30-27edb54ec62f.png)
You could just change the background of the corners from black to transparent. This should preserve those white borders.

**Comment by tengwar** [comment]
Basically remove lines 162 and 170 (e.g. those containing "-panel-corner-border-color") from extension.js.

**Comment by AMDG2** [comment]
Can you try your modification and submit a pull request ?

**Comment by tengwar** [comment]
OK, I did it.
