### ISSUE TITLE
When icon instead of Activities 

### ISSUE THREAD

**Issue by alex285** [AMDG2/GnomeShell_DynamicTopBar#17]
When no full screen, activities keyword is visible, while is hidden by theme CSS. 
Example theme:
https://github.com/alex285/evopop-shell-dist 

And the CSS
https://github.com/alex285/evopop-gnome-shell-theme/blob/master/stylus/panel.styl

![dynamic-bar-bug](https://cloud.githubusercontent.com/assets/11244308/7780040/e02fc088-00e2-11e5-9c49-2e0c66a8b1bc.png)

**Comment by AMDG2** [comment]
Ok, I need some help to understand your CSS, which part is used to hide the "Activities" text and display an icon instead ?

**Comment by alex285** [comment]
@AMDG2 It makes it invisible, by setting opacity to 0. 
#panelActivities
	color rgba(0,0,0,0.0)

**Comment by AMDG2** [comment]
Ok, I see, I will try to publish a fix asap.

Thanks for your bug report :)
