### ISSUE TITLE
gnome-tweak-tool reports "error loading extension" in Ubuntu 14.04

### ISSUE THREAD

**Issue by fossfreedom** [AMDG2/GnomeShell_DynamicTopBar#23]
Using Ubuntu 14.04 (Gtk+3.10), gnome-tweak-tool just reports the above error.

How can I help you diagnose the issue - are there any error logs I can give you?

**Comment by blandin** [comment]
I am also experiencing this issue.

**Comment by AMDG2** [comment]
What Gnome-Shell version are you using ?

**Comment by blandin** [comment]
```
$ gnome-shell --version
GNOME Shell 3.10.4
```

**Comment by AMDG2** [comment]
Ok, maybe I use some new API that was not supported at the G3.10 times...
I use Archlinux, so I do not have chance to try the extension on Ubuntu, and this old version of gnome.

Can you try to get some debug info from Looking Glass utility ?

**Comment by bmafy** [comment]
Have you figured out this problem? I get the same error as others get with the same gnome version :(

Thank you very much,
Mat

**Comment by AMDG2** [comment]
Ubuntu 14.04 is using a very old version of Gnome Shell and is going to be replaced by a new LTS version soon. I won't spend time working on this error. But you may try to use an old version (see releases page) of the extension.
