### ISSUE TITLE
Border-image not overwritten

### ISSUE THREAD

**Issue by zagortenay333** [AMDG2/GnomeShell_DynamicTopBar#24]
Some themes (https://github.com/zagortenay333/ciliora-tertia-shell) use the border image property for the panel, which doesn't get overwritten.

Could you add this?

**Comment by AMDG2** [comment]
The last version add a CSS class to the top bar. You should use it in your theme.
See this commit message for info : https://github.com/AMDG2/GnomeShell_DynamicTopBar/commit/805909535f038586dca4812b68f22b918eaf197c

**Comment by AMDG2** [comment]
@zagortenay333 Did you update your theme, so it works with the extension ? I would like to close the issue only if your problem was solved.

**Comment by zagortenay333** [comment]
Yeah it's fine.
