### ISSUE TITLE
GNOME 3.18 Support

### ISSUE THREAD

**Issue by sukso96100** [AMDG2/GnomeShell_DynamicTopBar#28]
Seems like this extension is not working with gnome 3.18 yet.
Since gnome 3.18 is just released. you may need to add gnome 3.18 support.
![2015-09-25 23-06-06](https://cloud.githubusercontent.com/assets/1916739/10102560/152eb8a2-63da-11e5-894b-c706dc321c3f.png)

**Comment by frandieguez** [comment]
+1
