### ISSUE TITLE
Extension does not works on GNOME 3.18.1/3.18.2

### ISSUE THREAD

**Issue by AnDroidEL** [AMDG2/GnomeShell_DynamicTopBar#31]
Hello,

I am using the Fedora 23 with GNOME 3.18.1, everything up to date. I have been downloaded and installed the extension but the gnome-tweak-tool do not found the extension installed on my system.

**Comment by sinedoOo** [comment]
I have exactly the same issue, Fedora 23 with Gnome 3.18.1

**Comment by mankurt** [comment]
+1

**Comment by bil-elmoussaoui** [comment]
Just add `3.18.1`to the metadata file :P

**Comment by AnDroidEL** [comment]
@bil-elmoussaoui Fedora 23 on GNOME 3.18.2 is not working too. :disappointed:

**Comment by AMDG2** [comment]
It should work now. I added 3.18 to metadata. The new release is available here: https://extensions.gnome.org/extension/885/dynamic-top-bar/
