### ISSUE TITLE
Transparency has no effect if a maximized application is present

### ISSUE THREAD

**Issue by hashhar** [AMDG2/GnomeShell_DynamicTopBar#32]
Take a look at these two to see what I mean. I have no idea why this happens (if it is a GNOME limitation or something else).

![screenshot from 2015-12-04 22-21-58](https://cloud.githubusercontent.com/assets/10473142/11595414/7de27eba-9ad5-11e5-9c6d-606e0cf7a951.png)
![screenshot from 2015-12-04 22-22-12](https://cloud.githubusercontent.com/assets/10473142/11595420/8848ca6c-9ad5-11e5-98b2-9c3e1076287a.png)

**Comment by JuanSeabra** [comment]
well, I think that is the point of this extension. The transparency only works when there are no windows maximized and trigger when you maximize a window, just like phanteon on ElementaryOS

**Comment by hashhar** [comment]
Oh, ok. Thanks. Maybe I'll fork it to behave that way. :)
