### ISSUE TITLE
Update metadata.json to support GNOME Shell 3.18

### ISSUE THREAD

**Issue by Diel1024** [AMDG2/GnomeShell_DynamicTopBar#33]
I'm using Arch Linux and have the latest version of shell. So, I was unable to use this extension because it supports versions up to 3.16 but not 3.18. I manually changed metadata.json, so I was able to enable extension. And *it works*! You don't need to do any changes in code, just update that file so more users will be able to install&use the extension. Thanks

UPD: Sorry, you've already done that, I didn't see. You may close this issue

**Comment by AMDG2** [comment]
No problem, I am going to release a new version of the extension on the Gnome Official repository.
