### ISSUE TITLE
Something wrong in Preferences

### ISSUE THREAD

**Issue by frnogueira** [AMDG2/GnomeShell_DynamicTopBar#34]
Hi!
My extension preferences appear like this:
![captura de tela de 2016-02-04 16-14-55](https://cloud.githubusercontent.com/assets/2768725/12826667/eb351cec-cb5a-11e5-98ef-0aca956b798d.png)
What is wrong? My locale is pt_BR and I translate this extension.

**Comment by ouafnico** [comment]
Same here ;) 
If I can try a future version please tell.

**Comment by AMDG2** [comment]
Fixed in version 17.
