### ISSUE TITLE
3.20 support

### ISSUE THREAD

**Issue by nos1609** [AMDG2/GnomeShell_DynamicTopBar#36]
Awaiting for Gnome 3.20 support. Thank You!

**Comment by AMDG2** [comment]
Gnome 3.20 is not event landing in ArchLinux (which I use), please update manually the metadata.json to support 3.20 and tell me if its working.

**Comment by nos1609** [comment]
It's already available in [gnome-unstable] ;)

Already done and work as intended.
![2016-03-31 10-28-14](https://cloud.githubusercontent.com/assets/11856987/14168493/ca703e2e-f733-11e5-91a6-55b366d714fd.png)

**Comment by AMDG2** [comment]
OK, i will update the file.
Thanks for your help

Le 31 mars 2016 09:29:25 GMT+02:00, Aleksei Nosachev <notifications@github.com> a écrit :
>It's already available in [gnome-unstable] ;)
>
>Already done and work as intended.
>![2016-03-31
>10-28-14](https://cloud.githubusercontent.com/assets/11856987/14168493/ca703e2e-f733-11e5-91a6-55b366d714fd.png)
>
>
>
>
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/AMDG2/GnomeShell_DynamicTopBar/issues/36#issuecomment-203796324

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by mckennajones** [comment]
Editing hte metadata.json file did not solve the issue for me. I'm also running ArchLinux.

**Comment by mckennajones** [comment]
Editing the metadata.json value did indeed solve the issue for me in ArchLinux
