### ISSUE TITLE
Ajouter le mot "Transparent" dans la description 

### ISSUE THREAD

**Issue by nath5394** [AMDG2/GnomeShell_DynamicTopBar#37]
Salut, 
Tu pourrais ajouter le mot "transparent" dans la description sur le site de Gnome Extension, car il n'y est pas et donc ça n'est pas très pratique pour trouver l'extension. (Il y a juste "Dynamic Top Bar" comme mots-clé)
Allez bon we !
NH

**Comment by AMDG2** [comment]
Merci !
