### ISSUE TITLE
Not working on 3.20.2

### ISSUE THREAD

**Issue by joaoherberto** [AMDG2/GnomeShell_DynamicTopBar#41]
Does not work on Gnome-Shell 3.20.2, running Manjaro Linux 64.
I have tried installing locally using extensions.gnome.org and using the AUR and installing system wide. Does not trigger the transparency.

**Comment by AMDG2** [comment]
Thanks for reporting the bug. I have some questions : 

- Does the extension load successfully ?
- Do you have a theme enabled ? If yes where can I find it ?

If the extension load successfully can you describe me what you are doing to "trigger the transparency" ?

**Comment by joaoherberto** [comment]
Yes, the extension loads successfully, 
I am running theme: **Vertex-Maia-Dark**
Icon Theme: **Elementary**
Shell THeme: **Vertex-Maia**

Here is the link to the official theme: http://horst3180.deviantart.com/art/Vertex-Theme-470663601
Plus the additional changes for Manjaro here: https://github.com/manjaro?utf8=%E2%9C%93&query=Maia

**Comment by AMDG2** [comment]
It seems that the theme is using background image to style the panel.
Can you report an issue in the repository of your theme referencing this issue and the following commit message : 805909535f038586dca4812b68f22b918eaf197c

The theme designer should change its image, or make the panel transparent/gradient when the following CSS classes are added to the panel:

- `dynamic-top-bar-transparency`
- `dynamic-top-bar-gradient`
