### ISSUE TITLE
"CRITICAL" Gnome-Shell Errors in system log due to dynamic top bar extension

### ISSUE THREAD

**Issue by farao** [AMDG2/GnomeShell_DynamicTopBar#42]
Hey,

I recently had a look into my systemlog (using journalctl -xe) and I found a lot of CRITICAL gnome shell errors (see [gnome-shell-errors.txt](https://github.com/AMDG2/GnomeShell_DynamicTopBar/files/502878/gnome-shell-errors.txt), not quite sure if the first two three lines belong to it). They appear every time that I open the gnome shell overview and by disabling all my extensions one by one I discovered that they are produced by this extension. What are they about? I'm running on a Gnome 3.20 (no difference between wayland and X11).

Yours,
Marius

**Comment by AMDG2** [comment]
I don't know why these errors appears. This extension is JS, and the error seems to came from C code. It will be hard to debug.
If the extension is still working I won't investigate on this.
