### ISSUE TITLE
Shadows aren't properly assigned when a window touches the topbar

### ISSUE THREAD

**Issue by espectalll** [AMDG2/GnomeShell_DynamicTopBar#52]
When a window is dragged, GNOME Shell tries to change its shadows in a way which leaves inconsistencies when using the dynamic top bar extension. This is especially noticeable when the button shadow option is disabled:

![image](https://user-images.githubusercontent.com/2456419/41409079-742156be-6fc4-11e8-86d8-05072553297b.png)
![image](https://user-images.githubusercontent.com/2456419/41409081-76c41c30-6fc4-11e8-9074-24450d523b41.png)

It also happens when it is enabled, though - pay attention to the application icon

![image](https://user-images.githubusercontent.com/2456419/41409463-d704c486-6fc5-11e8-98bd-6b372fb81e19.png)
![image](https://user-images.githubusercontent.com/2456419/41409468-da0352e2-6fc5-11e8-8443-66b5617322ec.png)

**Comment by espectalll** [comment]
OK, applying this CSS as a GNOME Shell theme largely fixes the issue:

```css
stage, stage * {
    -gtk-icon-shadow: none;
    icon-shadow: none;
    text-shadow: none;
}
```

The only thing that keeps failing is the icon's shadow, which is not being applied when "button shadow" is enabled. Apparently you have to apply the `icon-shadow` property to `.app-menu-icon` as shown at https://github.com/GNOME/gnome-shell-sass/blob/master/_common.scss#L780

**Comment by AMDG2** [comment]
Hello thank you for taking time to report this issue, but I am sorry I do not develop this extension anymore the feature is available in recent version of Gnome. Feel free to fork the extension if you need it on older version.

**Comment by espectalll** [comment]
OK thank you, although GNOME does not provide the same amount of control over the transparency the by default, you still have to rely on custom JS and/or CSS.

**Comment by AMDG2** [comment]
Yes sure. If you want to take over the maintenance of the extension feel free to ask for write access in the repo. I can also upload your updates to extensions.gnome.org so updates will be smooth.

Regards 

Le 20 juin 2018 14:49:09 GMT+02:00, "Francisco Gómez García" <notifications@github.com> a écrit :
>OK thank you, although GNOME does not provide the same amount of
>control over the transparency the by default, you still have to rely on
>custom JS and/or CSS.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/AMDG2/GnomeShell_DynamicTopBar/issues/52#issuecomment-398736685

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
