### ISSUE TITLE
Dynamic Top Bar doesn't work on GNOME3.30

### ISSUE THREAD

**Issue by Oslint** [AMDG2/GnomeShell_DynamicTopBar#53]
On GNOME3.30 Dynamic Top Bar is not working.

**Comment by opiumartdirectdesign** [comment]
me too...

**Comment by donovansolms** [comment]
From `journalctl -f /usr/bin/gnome-shell`

```gnome-shell[2353]: Extension "dynamicTopBar@gnomeshell.feildel.fr" had error: TypeError: global.screen is undefined```

**Comment by AMDG2** [comment]
Fixed by #54
