### ISSUE TITLE
error in gnome 3.30

### ISSUE THREAD

**Issue by lpf-gavin** [AMDG2/GnomeShell_DynamicTopBar#55]
In gnome 3.30, it can not work.

**Comment by catb0t** [comment]
Updated to Ubuntu 18.10 with GNOME 3.30.1 and the extension errors, I can try to get a log soon

**Comment by catb0t** [comment]
https://github.com/franglais125/no-title-bar/issues/93

**Comment by AMDG2** [comment]
From README.md:

# DISCLAIMER

This extension was usefull back in the days, but now that Gnome has included a similar feature I didn't need it anymore. If you want to takeover the maintenance and the development feel free to open an issue to discuss that topic.

I will only continue to merge pull-request for translations, maybe bugfixes or new features, but I will not fix bugs or implement new features myself.
