### ISSUE TITLE
Request: Resume active development, the built-in functionality has been removed from Gnome Shell 3.32 

### ISSUE THREAD

**Issue by nikolowry** [AMDG2/GnomeShell_DynamicTopBar#58]
Source: 
https://www.omgubuntu.co.uk/2019/02/gnome-shell-translucent-top-panel-effect-removed

Not the biggest fan of them removing this feature, but hopefully it might inspire you to get this project rolling again.

**Comment by ndmax** [comment]
This extension is worth reanimating.  Thanks @AMDG2 for making it in the first place.

**Comment by AMDG2** [comment]
Hi @nikolowry you already participated in the development, would you like to take over this extension ?

**Comment by nikolowry** [comment]
@Amdg2 I'd love to, but with my schedule I know I'll be a more maintainer. I also prefer a tiling WM these days and only occassionally log into a Gnome Shell DE.

After opening this, I did find a good alternative in https://github.com/rockon999/dynamic-panel-transparency. Maybe adding a link to it in the README might help anyone stumbling onto this repo
